apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  labels:
    storageos.com/replicas: "1"
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
